const express = require("express");
const verifyFirebaseToken = require("../middleware/authMiddleware");
const requireAdmin = require("../middleware/adminMiddleware");
const asyncHandler = require("../utils/asyncHandler");
const adminAccountController = require("../controllers/adminAccountController");
const adminReportController = require("../controllers/adminReportController");
const adminReviewController = require("../controllers/adminReviewController");
const adminNotificationController = require("../controllers/adminNotificationController");
const adminDashboardController = require("../controllers/adminDashboardController");
const adminCatalogController = require("../controllers/adminCatalogController");
const adminReservationController = require("../controllers/adminReservationController");
const adminInsightController = require("../controllers/adminInsightController");
const adminFollowController = require("../controllers/adminFollowController");

const router = express.Router();

router.get(
  "/dashboard",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminDashboardController.getDashboard)
);
router.get(
  "/accounts/statistics",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminAccountController.getAccountStatistics)
);
router.get(
  "/accounts",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminAccountController.listAccounts)
);

router.get(
  "/accounts/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminAccountController.getAccountDetail)
);
router.get(
  "/accounts/:id/history",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminInsightController.getAccountHistory)
);
router.get(
  "/accounts/:id/finance",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminInsightController.getAccountFinance)
);
router.get(
  "/accounts/:id/following",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminFollowController.listAccountFollowing)
);
router.get(
  "/accounts/:id/followers",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminFollowController.listAccountFollowers)
);
router.get(
  "/finance/overview",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminInsightController.getFinanceOverview)
);
router.get(
  "/audit-logs",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminInsightController.listAuditLogs)
);
router.post(
  "/accounts/:id/block",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminAccountController.blockAccount)
);
router.post(
  "/accounts/:id/unblock",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminAccountController.unblockAccount)
);

router.get("/shops", verifyFirebaseToken, requireAdmin, asyncHandler(adminCatalogController.listShops));
router.get(
  "/shops/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.getShopDetail)
);
router.get(
  "/shops/:id/history",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminInsightController.getShopHistory)
);
router.get(
  "/shops/:id/following",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminFollowController.listShopFollowing)
);
router.get(
  "/shops/:id/followers",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminFollowController.listShopFollowers)
);
router.post(
  "/shops/:id/block",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.blockShop)
);
router.post(
  "/shops/:id/unblock",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.unblockShop)
);
router.delete(
  "/shops/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.deleteShop)
);

router.get(
  "/products",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.listProducts)
);
router.get(
  "/products/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.getProductDetail)
);
router.post(
  "/products/:id/hide",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.hideProduct)
);
router.post(
  "/products/:id/show",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.showProduct)
);
router.delete(
  "/products/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminCatalogController.deleteProduct)
);

router.get(
  "/reservations",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.listReservations)
);
router.get(
  "/reservations/disputes",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.listDisputes)
);
router.get(
  "/reservations/stats",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.getReservationStats)
);
router.get(
  "/reservations/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.getReservationDetail)
);
router.post(
  "/reservations/:id/refund",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.refundToBuyer)
);
router.post(
  "/reservations/:id/release",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.releaseToSeller)
);
router.post(
  "/reservations/:id/cancel",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReservationController.cancelReservation)
);

router.get(
  "/reports",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.listReports)
);
router.get(
  "/reports/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.getReportDetail)
);
router.post(
  "/reports/:id/dismiss",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.dismissReport)
);
router.post(
  "/reports/:id/approve",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.approveReport)
);
/** Tranh chấp giữ hàng: hoàn cọc buyer. */
router.post(
  "/reports/:id/approve-buyer",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.approveBuyer)
);
/** Tranh chấp giữ hàng: giải ngân seller. */
router.post(
  "/reports/:id/approve-seller",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.approveSeller)
);
/** Tranh chấp giữ hàng: bác bỏ report, ghi log. */
router.post(
  "/reports/:id/reject",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReportController.rejectReservationReport)
);

router.get(
  "/reviews",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReviewController.listReviews)
);
router.get(
  "/reviews/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReviewController.getReviewDetail)
);
router.post(
  "/reviews/:id/hide",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReviewController.hideReview)
);
router.post(
  "/reviews/:id/show",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReviewController.showReview)
);
router.delete(
  "/reviews/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminReviewController.deleteReview)
);

router.post(
  "/notifications/broadcast",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminNotificationController.sendSystemNotification)
);
router.get(
  "/notifications/history",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(adminNotificationController.listBroadcastHistory)
);

const sellerPlanController = require("../controllers/sellerPlanController");
router.get(
  "/seller-plans",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.listAdminPlans)
);
router.post(
  "/seller-plans",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.createPlan)
);
router.put(
  "/seller-plans/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.updatePlan)
);
router.delete(
  "/seller-plans/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.removePlan)
);
router.get(
  "/seller-subscriptions",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.listSubscriptions)
);

// Legacy aliases
router.get(
  "/subscription-plans",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.listAdminPlans)
);
router.post(
  "/subscription-plans",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.createPlan)
);
router.put(
  "/subscription-plans/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.updatePlan)
);
router.delete(
  "/subscription-plans/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerPlanController.removePlan)
);

const sellerBannerController = require("../controllers/sellerBannerController");
router.get(
  "/banner-plans",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.listAdminPlans)
);
router.post(
  "/banner-plans",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.createPlan)
);
router.put(
  "/banner-plans/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.updatePlan)
);
router.delete(
  "/banner-plans/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.removePlan)
);
router.get(
  "/seller-banners",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.listSellerBanners)
);
router.post(
  "/seller-banners/:id/approve",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.approveSellerBanner)
);
router.post(
  "/seller-banners/:id/reject",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.rejectSellerBanner)
);
router.post(
  "/seller-banners/:id/cancel",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(sellerBannerController.cancelSellerBanner)
);

const bankController = require("../controllers/bankController");
router.get("/banks", verifyFirebaseToken, requireAdmin, asyncHandler(bankController.listBanks));
router.post("/banks", verifyFirebaseToken, requireAdmin, asyncHandler(bankController.createBank));
router.put(
  "/banks/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(bankController.updateBank)
);
router.delete(
  "/banks/:id",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(bankController.deleteBank)
);

const withdrawController = require("../controllers/withdrawController");
router.get(
  "/withdraws",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(withdrawController.listAdminWithdraws)
);
router.post(
  "/withdraws/:id/approve",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(withdrawController.approveWithdraw)
);
router.post(
  "/withdraws/:id/reject",
  verifyFirebaseToken,
  requireAdmin,
  asyncHandler(withdrawController.rejectWithdraw)
);

module.exports = router;
