export const API_ENDPOINTS = {
  root: '/',
  profile: '/profile',
  product: (id) => `/api/products/${id}`,
  authRegisterEmail: '/api/auth/register/email',
  authRegisterAvailability: '/api/auth/register/availability',
  authLoginEmail: '/api/auth/login/email',
  authGoogle: '/api/auth/google',
  authMe: '/api/auth/me',
  authUpdateMe: '/api/auth/me',
  authUploadAvatar: '/api/auth/avatar',
  authVerifyEmailRequest: '/api/auth/verify-email/request',
  authVerifyEmailConfirm: '/api/auth/verify-email/confirm',
  presenceOnline: '/api/auth/presence/online',
  presenceOffline: '/api/auth/presence/offline',
  shopPresenceOnline: '/api/auth/presence/shop/online',
  shopPresenceOffline: '/api/auth/presence/shop/offline',
  sellerPhoneCodeRequest: '/api/seller/phone-code/request',
  sellerPhoneCodeConfirm: '/api/seller/phone-code/confirm',
  sellerVerificationMe: '/api/seller/verification/me',
  sellerVerificationSubmit: '/api/seller/verification',
  productCategories: '/api/products/categories',
  adminProductCategories: '/api/categories/products',
  adminShopCategories: '/api/categories/shops',
  products: '/api/products',
  productsDiscover: '/api/products/discover',
  productById: (id) => `/api/products/${id}`,
  myProductById: (id) => `/api/products/mine/${id}`,
  sellerShop: '/api/seller/shop',
  sellerShopAvatar: '/api/seller/shop/avatar',
  sellerShopUsernameAvailability: '/api/seller/shop/username-availability',
  sellerOrders: '/api/seller/orders',
  sellerReservation: (id) => `/api/seller/reservations/${id}`,
  sellerReservationConfirm: (id) => `/api/seller/reservations/${id}/confirm`,
  sellerReservationReject: (id) => `/api/seller/reservations/${id}/reject`,
  sellerReservationCancel: (id) => `/api/seller/reservations/${id}/cancel`,
  sellerReservationComplete: (id) => `/api/seller/reservations/${id}/complete`,
  sellerReservationScanComplete: '/api/seller/reservations/scan-complete',
  sellerConversations: '/api/seller/conversations',
  sellerConversationMessages: (id) => `/api/seller/conversations/${id}/messages`,
  sellerConversationMessage: (conversationId, messageId) =>
    `/api/seller/conversations/${conversationId}/messages/${messageId}`,
  sellerConversationPeer: (id) => `/api/seller/conversations/${id}/peer`,
  sellerStats: '/api/seller/stats',
  sellerSubscription: '/api/seller/subscription',
  sellerSubscriptionPurchase: '/api/seller/subscription/purchase',
  sellerVouchers: '/api/seller/vouchers',
  sellerVoucher: (id) => `/api/seller/vouchers/${id}`,
  buyerConversations: '/api/buyer/conversations',
  buyerConversationMessages: (id) => `/api/buyer/conversations/${id}/messages`,
  buyerConversationMessage: (conversationId, messageId) =>
    `/api/buyer/conversations/${conversationId}/messages/${messageId}`,
  buyerConversationPeer: (id) => `/api/buyer/conversations/${id}/peer`,
  buyerShops: '/api/buyer/shops',
  buyerFavorites: '/api/buyer/favorites',
  buyerFavoriteIds: '/api/buyer/favorites/ids',
  buyerFavorite: (productId) => `/api/buyer/favorites/${productId}`,
  buyerFollows: '/api/buyer/follows',
  buyerFollowStatus: '/api/buyer/follows/status',
  buyerFollowing: '/api/buyer/follows/following',
  buyerFollowers: '/api/buyer/follows/followers',
  buyerFollow: (shopId) => `/api/buyer/follows/${shopId}`,
  buyerReviews: '/api/buyer/reviews',
  buyerReview: (id) => `/api/buyer/reviews/${id}`,
  buyerReports: '/api/buyer/reports',
  buyerOrders: '/api/buyer/orders',
  buyerReservations: '/api/buyer/reservations',
  buyerReservation: (id) => `/api/buyer/reservations/${id}`,
  buyerReservationCancel: (id) => `/api/buyer/reservations/${id}/cancel`,
  buyerReservationComplete: (id) => `/api/buyer/reservations/${id}/complete`,
  buyerVouchers: '/api/buyer/vouchers',
  buyerVouchersNearby: '/api/buyer/vouchers/nearby',
  bannersActive: '/api/banners/active',
  wallet: '/api/wallet',
  walletTransactions: '/api/wallet/transactions',
  walletTransaction: (id) => `/api/wallet/transactions/${id}`,
  walletTopup: '/api/wallet/topup',
  walletTopupSync: '/api/wallet/topup/sync',
  authForgotPasswordRequest: '/api/auth/forgot-password/request',
  authForgotPasswordVerify: '/api/auth/forgot-password/verify',
  authForgotPasswordReset: '/api/auth/forgot-password/reset',
  shopsNearby: '/api/shops/nearby',
  shopsSearch: '/api/shops/search',
  shopCategories: '/api/shops/categories',
  shopById: (id) => `/api/shops/${id}`,
  shopProducts: (id) => `/api/shops/${id}/products`,
  shopReviews: (id) => `/api/shops/${id}/reviews`,
  notifications: '/api/notifications',
  notificationRead: (id) => `/api/notifications/${id}/read`,
  notificationsReadAll: '/api/notifications/read-all',
};
