export const API_ENDPOINTS = {
  root: '/',
  product: (id) => `/api/products/${id}`,
  authRegisterEmail: '/api/auth/register/email',
  authRegisterAvailability: '/api/auth/register/availability',
  authLoginEmail: '/api/auth/login/email',
  authGoogle: '/api/auth/google',
  authMe: '/api/auth/me',
  authUpdateMe: '/api/auth/me',
  authLockAppeal: '/api/auth/lock-appeal',
  authShopLockAppeal: '/api/auth/shop-lock-appeal',
  authUploadAvatar: '/api/auth/avatar',
  authVerifyEmailRequest: '/api/auth/verify-email/request',
  authVerifyEmailConfirm: '/api/auth/verify-email/confirm',
  presenceOnline: '/api/auth/presence/online',
  presenceOffline: '/api/auth/presence/offline',
  shopPresenceOnline: '/api/auth/presence/shop/online',
  shopPresenceOffline: '/api/auth/presence/shop/offline',
  sellerPhoneCodeRequest: '/api/seller/phone-code/request',
  sellerPhoneCodeConfirm: '/api/seller/phone-code/confirm',
  sellerVerificationMe: '/api/seller/verification/me',
  sellerVerificationSubmit: '/api/seller/verification',
  productCategories: '/api/products/categories',
  adminProductCategories: '/api/categories/products',
  adminShopCategories: '/api/categories/shops',
  products: '/api/products',
  productsDiscover: '/api/products/discover',
  productById: (id) => `/api/products/${id}`,
  myProductById: (id) => `/api/products/mine/${id}`,
  sellerShop: '/api/seller/shop',
  sellerShopAvatar: '/api/seller/shop/avatar',
  sellerShopUsernameAvailability: '/api/seller/shop/username-availability',
  sellerOrders: '/api/seller/orders',
  sellerReviews: '/api/seller/reviews',
  sellerReview: (id) => `/api/seller/reviews/${id}`,
  sellerReservation: (id) => `/api/seller/reservations/${id}`,
  sellerReservationConfirm: (id) => `/api/seller/reservations/${id}/confirm`,
  sellerReservationReject: (id) => `/api/seller/reservations/${id}/reject`,
  sellerReservationCancel: (id) => `/api/seller/reservations/${id}/cancel`,
  sellerReservationRefundDispute: (id) => `/api/seller/reservations/${id}/refund-dispute`,
  sellerReservationValidatePickupQr: '/api/seller/reservations/validate-pickup-qr',
  sellerReservationConfirmDelivered: (id) => `/api/seller/reservations/${id}/confirm-delivered`,
  sellerReservationAdjustAtPickup: (id) => `/api/seller/reservations/${id}/adjust-at-pickup`,
  sellerReservationDisputeResponse: (id) => `/api/seller/reservations/${id}/dispute-response`,
  sellerReservationReportBuyer: (id) => `/api/seller/reservations/${id}/report-buyer`,
  sellerConversations: '/api/seller/conversations',
  sellerConversationMessages: (id) => `/api/seller/conversations/${id}/messages`,
  sellerConversationMessage: (conversationId, messageId) =>
    `/api/seller/conversations/${conversationId}/messages/${messageId}`,
  sellerConversationPeer: (id) => `/api/seller/conversations/${id}/peer`,
  sellerStats: '/api/seller/stats',
  sellerSubscription: '/api/seller/subscription',
  sellerSubscriptionPurchase: '/api/seller/subscription/purchase',
  sellerBanner: '/api/seller/banner',
  sellerBannerPurchase: '/api/seller/banner/purchase',
  sellerBannerCreative: '/api/seller/banner/creative',
  buyerConversations: '/api/buyer/conversations',
  buyerConversationMessages: (id) => `/api/buyer/conversations/${id}/messages`,
  buyerConversationMessage: (conversationId, messageId) =>
    `/api/buyer/conversations/${conversationId}/messages/${messageId}`,
  buyerConversationPeer: (id) => `/api/buyer/conversations/${id}/peer`,
  buyerShops: '/api/buyer/shops',
  buyerFavorites: '/api/buyer/favorites',
  buyerFavoriteIds: '/api/buyer/favorites/ids',
  buyerFavorite: (productId) => `/api/buyer/favorites/${productId}`,
  buyerFollows: '/api/buyer/follows',
  buyerFollowStatus: '/api/buyer/follows/status',
  buyerFollowing: '/api/buyer/follows/following',
  buyerFollowers: '/api/buyer/follows/followers',
  buyerFollow: (shopId) => `/api/buyer/follows/${shopId}`,
  buyerUsersSearch: '/api/buyer/users/search',
  buyerUserProfile: (userId) => `/api/buyer/users/${userId}`,
  buyerUserFollowing: (userId) => `/api/buyer/users/${userId}/following`,
  buyerReviews: '/api/buyer/reviews',
  buyerReview: (id) => `/api/buyer/reviews/${id}`,
  buyerReports: '/api/buyer/reports',
  buyerOrders: '/api/buyer/orders',
  buyerReservations: '/api/buyer/reservations',
  buyerReservation: (id) => `/api/buyer/reservations/${id}`,
  buyerReservationCancel: (id) => `/api/buyer/reservations/${id}/cancel`,
  buyerReservationConfirmReceived: '/api/buyer/reservations/confirm-received',
  buyerReservationValidateShopQr: '/api/buyer/reservations/validate-shop-qr',
  buyerReservationReport: '/api/buyer/reservations/report',
  buyerReservationConfirmReceivedById: (id) => `/api/buyer/reservations/${id}/confirm-received`,
  buyerReservationReportById: (id) => `/api/buyer/reservations/${id}/report`,
  buyerReservationForfeitDeposit: '/api/buyer/reservations/forfeit-deposit',
  buyerReservationForfeitDepositById: (id) => `/api/buyer/reservations/${id}/forfeit-deposit`,
  reservationDisputeReports: (id) => `/api/reports/reservation/${id}`,
  buyerReportSeller: '/api/reports/buyer-report-seller',
  sellerReportBuyer: '/api/reports/seller-report-buyer',
  bannersActive: '/api/banners/active',
  bannerClick: '/api/banners',
  productsPromotions: '/api/products/promotions',
  productsPromotionsMine: '/api/products/promotions/mine',
  productsPromotionsBulk: '/api/products/promotions/bulk',
  productPromotion: (id) => `/api/products/${id}/promotion`,
  productPin: (id) => `/api/products/${id}/pin`,
  shopPromotions: (id) => `/api/shops/${id}/promotions`,
  wallet: '/api/wallet',
  walletTransactions: '/api/wallet/transactions',
  walletTransaction: (id) => `/api/wallet/transactions/${id}`,
  walletTopup: '/api/wallet/topup',
  walletTopupSync: '/api/wallet/topup/sync',
  walletTopupCancel: '/api/wallet/topup/cancel',
  walletBanks: '/api/wallet/banks',
  walletWithdraw: '/api/wallet/withdraw',
  walletWithdraws: '/api/wallet/withdraws',
  authForgotPasswordRequest: '/api/auth/forgot-password/request',
  authForgotPasswordRequestMe: '/api/auth/forgot-password/request-me',
  authForgotPasswordVerify: '/api/auth/forgot-password/verify',
  authForgotPasswordReset: '/api/auth/forgot-password/reset',
  shopsNearby: '/api/shops/nearby',
  shopsSearch: '/api/shops/search',
  shopCategories: '/api/shops/categories',
  shopById: (id) => `/api/shops/${id}`,
  shopProducts: (id) => `/api/shops/${id}/products`,
  shopReviews: (id) => `/api/shops/${id}/reviews`,
  notifications: '/api/notifications',
  notificationsUnreadCount: '/api/notifications/unread-count',
  notificationRead: (id) => `/api/notifications/${id}/read`,
  notificationsReadAll: '/api/notifications/read-all',
  notificationDeviceToken: '/api/notifications/device-token',
};
