const RESERVATION_STATUS = {
  PENDING: 0,
  CONFIRMED: 1,
  COMPLETED: 2,
  CANCELLED: 3,
};

const BUYER_CANCEL_LOCK_MINUTES = 15;

module.exports = {
  RESERVATION_STATUS,
  BUYER_CANCEL_LOCK_MINUTES,
};
